# Book settings
title: M2 Signal classes
author: IMAC Students
logo: logo.png

repository:
  url: https://github.com/IMAC-projects/M2-SIS-signal

html:
  favicon : "favicon.ico"
  use_issues_button: true
  use_repository_button: true

only_build_toc_files: true
